### ISSUE TITLE
Favorite and Tag data cleared

### ISSUE THREAD

**Issue by Vernetzt** [rthomasv3/Scum-Bag#3]
Using the `Save Details` button clears any favorite backups and tags for that save.

1. Add favorite and/or tag to a backup
2. Update Details and `Save Details`
3. Select a different save or relaunch Scum Bag
4. Favorite/Tag should be cleared for that first save

**Comment by rthomasv3** [comment]
Thanks for reporting the issue and providing clear steps to reproduce. There was a [bug](https://github.com/rthomasv3/Scum-Bag/commit/b6d33b46024f23631efb6bd2ff0acd76ad0599a0) in the save details code that was overwriting the backup metadata. It should be fixed now in [Release v1.1.1](https://github.com/rthomasv3/Scum-Bag/releases/tag/v1.1.1)
