### ISSUE TITLE
[BUG] Enabled / Disabled status not saving.

### ISSUE THREAD

**Issue by Vernetzt** [rthomasv3/Scum-Bag#4]
Possibly related to #3 

**Problem:** Enabled and Disabled status fail to save

1. Enable or Disable a save
2. Select another save or restart Scum Bag
3. Enabled or Disabled status will revert

Manually updating `saves.json` works.
No errors in `logs.txt`

[v1.1.2](https://github.com/rthomasv3/Scum-Bag/releases/tag/v1.1.2)
Windows 11 23H2

**Additional:**
[v1.1.0](https://github.com/rthomasv3/Scum-Bag/releases/tag/v1.1.0) works as expected minus the metadata issue.

**Comment by rthomasv3** [comment]
Thanks for reporting the issue, looks like I accidentally introduced this as part of the metadata fix in v1.1.1.

I should have a fix out soon.

**Comment by rthomasv3** [comment]
Fixed in [Release v1.1.3](https://github.com/rthomasv3/Scum-Bag/releases/tag/v1.1.3)
